### PR TITLE
add contents section with links

### PR DESCRIPTION
**Pull request by Vandivier**

### CODE REVIEW

**Review by christianbundy — COMMENTED** [review]
I think a table of contents is a solid proposal, how would you feel about using something like the [markdown-toc](https://github.com/jonschlinkert/markdown-toc) format? It seems like the community has started to use that format ("Table of Contents" naming with unordered list) as the de facto standard.

**Comment by Vandivier** [comment]
Agreed, that is how the community is doing things.

I like an ordered list since the content appears in some order and it's useful to have sections numbered for reference, but community first, I'll mod my own repos

**Comment by christianbundy** [comment]
This looks great -- one last thing, would you mind using `-` rather than `*` for the unordered list? It seems like markdown-toc, doctoc, and even the CommonMark documentation use that symbol, so I think it would be best to follow. I used [this tool](https://ecotrust-canada.github.io/markdown-toc/) and here's what it spit out:

``` md
- [Installation](#installation)
- [Usage](#usage)
- [Support](#support)
- [Contributing](#contributing)
```

**Comment by Vandivier** [comment]
done, although now it doesn't match the unordered list under #usage

**Comment by christianbundy** [comment]
Good call, I didn't notice that. You're more than welcome to fix that in your PR, or I'll fix it in another PR. Your call. I really appreciate this contribution, thanks!

**Review by christianbundy — APPROVED** [review]

**Comment by Vandivier** [comment]
Added that as well - glad to help!

**Pull request merged**
